name: "Bug"
description: "Сообщите об ошибке в работе программы"
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Что произошло?"
      description: "Опишите проблему"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Что должно было произойти?"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "Версия программы"
      placeholder: "v1.0.0"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: "ОС"
      options:
        - "Linux"
        - "Windows"
        - "macOS"
    validations:
      required: true
