name: "Feature Request"
description: "Предложите новую функцию или улучшение"
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Описание"
      description: "Что вы хотите добавить?"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: "Приоритет"
      options:
        - "Низкий"
        - "Средний"
        - "Высокий"
    validations:
      required: true
