name: "Question"
description: "Задайте вопрос по использованию программы"
title: "[QUESTION]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: "Ваш вопрос"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "Версия (если применимо)"
      placeholder: "v1.0.0"
